/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119686-gae0f71a387-20250525"
#endif /* AVUTIL_FFVERSION_H */
